services:
  simple-rest-api:
    container_name: simple-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
  mysql:
    container_name: simple-rest-api-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - simple-rest-api-volume:/var/lib/mysql
      - ./src/infra/repositories/mysql/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=8840
      - MYSQL_DATABASE=simple_rest_api_db

volumes:
  simple-rest-api-volume:
