services:
  simple-rest-api:
    container_name: simple-rest-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      - PORT=5555
